"""Builds 02_pilot_data.sql from the pilot spreadsheet.

Usage (from the project root):
    py -m pip install openpyxl
    py supabase/database/tools/build_pilot_import.py "C:/path/to/Data for coding PuzzleBox.xlsx"

Every one of the 133 coded columns is kept, unchanged, in
pilot_screening_data.answers (JSON keyed by the spreadsheet header). The
decoded basics (school, age, gender, home language) also go onto the child's
row in `children` so the dashboards can count and filter them.
"""

import json
import sys
from pathlib import Path

import openpyxl

SHEET = "Form Responses 1"
HEADER_ROW = 5          # 1-based: the row holding Child, Hlang, Slang, ...
SECTION_ROW = 1         # Biographical Data, Screening Normalcy, ...
SUBSECTION_ROWS = (3, 4)  # COGNITIVE / LANGUAGE ..., Living Conditions ...
LAST_COLUMN = 133       # columns after this are empty

# From the "Codes" sheet.
GENDER = {1: "Male", 2: "Female"}
LANGUAGE = {1: "English", 2: "Afrikaans", 3: "isiXhosa", 4: "Shona", 5: "Other"}
PLACE_OF_TESTING = {
    1: "Fort Beaufort",
    2: "Port Elizabeth",
    3: "Adelaide",
    4: "Despatch",
    5: "Other Testing Site",
    6: "East London",
}
PROVINCE = "Eastern Cape"


def sql_text(value):
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def carry_forward(cells):
    """Section titles sit in the first cell of their block; repeat them across it."""
    out, current = [], None
    for value in cells:
        if value is not None and str(value).strip():
            current = str(value).strip()
        out.append(current)
    return out


def main(xlsx_path, out_path):
    ws = openpyxl.load_workbook(xlsx_path, data_only=True)[SHEET]
    rows = list(ws.iter_rows(values_only=True))
    headers = [str(h).strip() if h is not None else None for h in rows[HEADER_ROW - 1][:LAST_COLUMN]]
    assert all(headers), "an expected header cell is empty"
    assert len(set(headers)) == len(headers), "duplicate headers: answers would overwrite each other"
    assert headers[:7] == ["Child", "Hlang", "Slang", "Tlang", "AgeMths", "Gender", "ECD"], headers[:7]

    sections = carry_forward(rows[SECTION_ROW - 1][:LAST_COLUMN])
    section_starts = {i for i, v in enumerate(rows[SECTION_ROW - 1][:LAST_COLUMN]) if v is not None}

    # Subsection labels (COGNITIVE, Living Conditions, ...) carry across
    # columns until the next label or the next section. "TIME (...)" labels
    # describe only the single column they sit above.
    subsections = []
    current = {r: None for r in SUBSECTION_ROWS}
    for i in range(LAST_COLUMN):
        if i in section_starts:
            current = {r: None for r in SUBSECTION_ROWS}
        own_column_note = None
        for r in SUBSECTION_ROWS:
            v = rows[r - 1][i]
            if v is not None and str(v).strip():
                if str(v).strip().upper().startswith("TIME"):
                    own_column_note = str(v).strip()
                else:
                    current[r] = str(v).strip()
        parts = [current[r] for r in SUBSECTION_ROWS if current[r]] + ([own_column_note] if own_column_note else [])
        subsections.append(" / ".join(parts) or None)

    data = []
    for sheet_row, row in enumerate(rows[HEADER_ROW:], start=HEADER_ROW + 1):
        row = row[:LAST_COLUMN]
        if all(v is None for v in row):
            continue
        data.append((sheet_row, row))

    lines = [
        "-- 02_pilot_data.sql",
        "--",
        "-- GENERATED by tools/build_pilot_import.py from the pilot spreadsheet",
        f"-- ({len(data)} children, {LAST_COLUMN} columns). Do not edit by hand: re-run the script.",
        "--",
        "-- Adds every pilot child to `children` (data_source = 'pilot', no teacher, so",
        "-- only admins and psychologists see them) with a student number, and keeps",
        "-- all their coded answers in pilot_screening_data. The spreadsheet's child",
        "-- code (e.g. S121) is stored as the child's private name, like a real name.",
        "--",
        "-- Run after 01. Safe to run more than once (rows already imported are skipped).",
        "-- To remove it all again:  delete from public.children where data_source = 'pilot';",
        "",
        "begin;",
        "",
        "create table if not exists public.pilot_column_dictionary (",
        "  column_number int primary key,",
        "  column_key    text not null unique,",
        "  section       text,",
        "  subsection    text",
        ");",
        "",
        "create table if not exists public.pilot_screening_data (",
        "  child_id     uuid primary key references public.children(id) on delete cascade,",
        "  source_row   int  not null unique,",
        "  source_code  text not null,",
        "  answers      jsonb not null,",
        "  imported_at  timestamptz not null default now()",
        ");",
        "",
        "alter table public.pilot_column_dictionary enable row level security;",
        "alter table public.pilot_screening_data enable row level security;",
        "",
        "insert into public.pilot_column_dictionary (column_number, column_key, section, subsection) values",
    ]
    dict_rows = [
        f"  ({i + 1}, {sql_text(h)}, {sql_text(sections[i])}, {sql_text(subsections[i])})"
        for i, h in enumerate(headers)
    ]
    lines.append(",\n".join(dict_rows))
    lines += [
        "on conflict (column_number) do update",
        "  set column_key = excluded.column_key, section = excluded.section, subsection = excluded.subsection;",
        "",
        "create temporary table pilot_import (",
        "  source_row int, source_code text, school text, age_months int, gender text, home_language text, answers jsonb",
        ") on commit drop;",
        "",
        "insert into pilot_import values",
    ]

    under_one = []
    values = []
    for sheet_row, row in data:
        answers = dict(zip(headers, row))
        code = str(answers["Child"]).strip()
        months = int(answers["AgeMths"])
        if months < 12:
            under_one.append(f"{code} ({months})")
        values.append("  ({}, {}, {}, {}, {}, {}, {}::jsonb)".format(
            sheet_row,
            sql_text(code),
            sql_text(PLACE_OF_TESTING[int(answers["ECD"])]),
            months,
            sql_text(GENDER[int(answers["Gender"])]),
            sql_text(LANGUAGE[int(answers["Hlang"])]),
            sql_text(json.dumps(answers, ensure_ascii=False, default=str)),
        ))
    lines.append(",\n".join(values) + ";")

    codes = [str(r[0]).strip() for _, r in data]
    repeated = sorted({c for c in codes if codes.count(c) > 1})
    lines += [
        "",
        "do $$",
        "declare",
        "  r record;",
        "  s public.schools;",
        "  new_id uuid;",
        "  n_added int := 0;",
        "begin",
        "  for r in select * from pilot_import order by source_row loop",
        "    continue when exists (select 1 from public.pilot_screening_data where source_row = r.source_row);",
        f"    s := app.school_for(r.school, {sql_text(PROVINCE)});",
        "    insert into public.children (name, school_id, school, province, age, age_months, gender, language, examiner, data_source)",
        "    values (",
        "      -- the same code appears twice for different children; keep them apart",
        f"      case when r.source_code = any ({sql_text('{' + ','.join(repeated) + '}')}::text[])",
        "           then r.source_code || ' (row ' || r.source_row || ')' else r.source_code end,",
        f"      s.id, s.name, {sql_text(PROVINCE)}, r.age_months / 12, r.age_months, r.gender, r.home_language,",
        "      'Pilot study', 'pilot')",
        "    returning id into new_id;",
        "    insert into public.pilot_screening_data (child_id, source_row, source_code, answers)",
        "    values (new_id, r.source_row, r.source_code, r.answers);",
        "    n_added := n_added + 1;",
        "  end loop;",
        "  raise notice 'pilot children added: % (already there: %)', n_added,",
        "    (select count(*) from pilot_import) - n_added;",
        "end $$;",
        "",
        "commit;",
        "",
    ]
    if under_one:
        lines.insert(12, "-- CHECK: these ages are under 12 months in the spreadsheet and get numbers like FB-11M-0123.")
        lines.insert(13, "-- They look like years typed into the months column: " + ", ".join(under_one))

    Path(out_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path}: {len(data)} children; repeated codes {repeated}; under one year: {under_one}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    here = Path(__file__).resolve().parent.parent
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else here / "02_pilot_data.sql")
