// App.test.js is a testing file —
//  its job is to automatically check that the app is working correctly.
//npm testRuns your test files and checks if things work correctly 

// This file was auto-generated by create-react-app as a starter example.

// render is a function that loads a React component into a fake browser environment
// so you can inspect it without actually opening a real browser window.
//  behind-the-scenes screen that only the test can see.


import { render, screen } from '@testing-library/react';

// This imports your main App component so the test can render and inspect it.

import App from './App';


// First argument — a plain English description of what this test is checking.
// This is what gets printed in the terminal when you run npm test so you can
// see at a glance which tests passed and which failed.
// Second argument — an arrow function containing the actual test logic to run.
test('renders learn react link', () => {
  render(<App />);
  // render(<App />) takes the App component and loads it into the fake browser
  // environment behind the scenes. After this line runs, the full component tree
  // of your app exists in memory and screen can search through it.
  const linkElement = screen.getByText(/learn react/i);

  // screen.getByText() searches through everything currently rendered on the fake
  // screen and looks for an element that contains the text matching what you pass in.
  
  // If it finds a match it returns that element. If it finds nothing it throws an
  // error and the test automatically fails right here.

  expect(linkElement).toBeInTheDocument();

  // expect() is the assertion — this is where you actually declare what you believe
  // should be true. You pass in the element you found above and then chain
  // .toBeInTheDocument() which checks that the element exists on the page.
  // If it does, the test passes and you see a green checkmark in the terminal.
  // If it doesnt, the test fails and you see a red error telling you what went wrong.

});
